### ISSUE TITLE
Stylesheet is deleted when any element with the directive is unmounted

### ISSUE THREAD

**Issue by 021-projects** [webigorkiev/vue-touch-ripple#1]
**Reproduce example:**

```vue
<script setup lang="ts">
  const showRemoveBtn = ref(false)
</script>

<template>
  <div
    v-if="showRemoveBtn" 
    @click="showRemoveBtn = false"
    class="btn"
    v-touch-ripple
  >Click to remove</btn>
  <div class="btn" v-touch-ripple>Another button</btn>
</template>
```
After clicking on the remove button, the `removeSheet()` method will be called, which will remove the style sheet for both components.

**Suggested solution**
Mount the general style once, and specify the duration of the effect in the style attribute

**Comment by webigorkiev** [comment]
Thanks
Resolved in [1.1.3](https://github.com/webigorkiev/vue-touch-ripple/tree/v1.1.3)
